version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50000:8080"
    environment:
      - HEALTH_TRACKER_DB_PATH=/data/healthtracker.db
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - health-tracker-data:/data
    restart: unless-stopped

volumes:
  health-tracker-data:
